[package]
name = "choir-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
choir-hash = { path = "../choir-hash" }
fastcdc = "3"
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
